SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

DROP DATABASE IF EXISTS '128crud_db';

CREATE DATABASE IF NOT EXISTS '128crud_db'

USE '128crud_db';